Add data source health check
VolkovLabs/volkovlabs-grapi-datasource pull request #71
Opened 2024-07-12 09:58 UTC by asimonok

Resolves #62

2024-07-12 19:01 UTC, mikhail-vl commented on src/api/datasources.ts
> +        datasourcesHealth.push(await this.getHealthStatus(datasource.uid));
Should it be Promise.all to speed up if there are many of them?

2024-07-12 19:14 UTC, mikhail-vl commented on src/api/datasources.ts
> +        url: `${this.api.instanceSettings.url}/api/datasources/uid/${id}/health`,
Business Satellite returns `{"message":"Plugin unavailable","messageId":"plugin.unavailable","statusCode":500,"traceID":""}` when checking it's health.

2024-07-12 19:15 UTC, mikhail-vl requested changes
Business Satellite returns error for it's health-check:

![Screenshot 2024-07-12 at 3 14 52 PM](https://github.com/user-attachments/assets/e126004c-5bb9-4045-984f-a8596f7f1b24)

2024-07-15 10:02 UTC, asimonok commented on src/api/datasources.ts
> +        datasourcesHealth.push(await this.getHealthStatus(datasource.uid));
fixed

2024-07-15 10:02 UTC, asimonok commented on src/api/datasources.ts
> +        url: `${this.api.instanceSettings.url}/api/datasources/uid/${id}/health`,
fixed

2024-07-16 02:34 UTC, mikhail-vl approved these changes
Looks great!

2024-07-16 02:34 UTC, merged